version: "1"

run:
  go: "1.24"
  timeout: 5m
  tests: false
  concurrency: 0
  modules-download-mode: readonly
  allow-parallel-runners: true
  env:
    - CGO_ENABLED=0
output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
linters-settings:

  cyclop:
    max-complexity: 13
    skip-tests: true
  funlen:
    lines: 60
    statements: 40
  dupl:
    threshold: 200

  # —— API/错误处理 ——
  errcheck:
    check-type-assertions: true
  errorlint:
    comparison: false
    asserts: false

  # —— 性能/安全的小优化 ——
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  goimports:
    local-prefixes: github.com/jeffinity/singularity
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/jeffinity/singularity)
      - blank
      - dot

  forbidigo:
    forbid:
      - "^print$"
      - "^println$"
      - '^fmt\.Print.*'

skip-dirs:
  - vendor
  - deprecated
  - docs
  - proto_gen
  - third_party
  - dist
  - build
  - .git

skip-files:
  - ".*_test\\.go"
  - ".*\\.pb\\.go"
  - ".*\\.gen\\.go"
  - ".*zz_generated.*\\.go"

issues:
  severity:
    default-severity: warning
  severity-rules:
    - linters: [ govet, staticcheck, typecheck, errcheck, errorlint, ineffassign, unused, wastedassign, depguard ]
      severity: error
  exclude-rules:
    - text: "SA1019"
      linters:
        - staticcheck
    - path: vendor/.*
      text: ".*"
    - path: deprecated/.*
      text: ".*"
    - path: docs/.*
      text: ".*"
    - path: ".*_test\\.go"
      text: ".*"