version: '3'

vars:
  TOOLS_DIR: 'third_party/build-tools'

includes:
  common: third_party/build-tools/Taskfile.yml

tasks:
  check:
    desc: Env check
    cmds:
      - task: common:check
        silent: true

  format:
    desc: Format *go code
    deps: [check]
    cmds:
      - cmd: task common:format -- {{.CLI_ARGS}}
        silent: true

  format-app:
    desc: Format {app}/*go code
    deps: [check]
    cmds:
      - cmd: task common:format-app -- {{.CLI_ARGS}}
        silent: true

  lint:
    desc: Lint all code
    deps: [check]
    cmds:
      - cmd: task common:lint -- {{.CLI_ARGS}}
        silent: true

  conf:
    desc: Gen {app}/internal/conf/*.proto
    deps: [check]
    cmds:
      - cmd: task common:conf -- {{.CLI_ARGS}}
        silent: true

  wire:
    desc: wire gen selected {app}
    deps: [check]
    cmds:
      - cmd: task common:wire -- {{.CLI_ARGS}}
        silent: true

  wire-all:
    desc: wire gen all app
    deps: [check]
    cmds:
      - cmd: task common:wire-all -- {{.CLI_ARGS}}
        silent: true

  build:
    desc: build app for the native platform
    deps: [check]
    cmds:
      - cmd: task common:build -- {{.CLI_ARGS}}
        silent: true

  build-linux-amd64:
    desc: build app for the linux-amd64
    deps: [check]
    cmds:
      - cmd: task common:build-linux-amd64 -- {{.CLI_ARGS}}
        silent: true

  build-linux-arm64:
    desc: build app for the linux-arm64
    deps: [check]
    cmds:
      - cmd: task common:build-linux-arm64 -- {{.CLI_ARGS}}
        silent: true

  deploy:
    desc: build app to the server
    cmds:
      - cmd: task common:deploy -- {{.CLI_ARGS}}
        silent: true

  newapp:
    desc: create new app with app_layout
    deps: [check]
    cmds:
      - cmd: task common:newapp -- {{.CLI_ARGS}}
        silent: true
